/**
 * Excel (.xlsx) Export Generator
 *
 * Multi-sheet workbook using SheetJS (xlsx).
 * Dynamically imported to avoid bundle bloat.
 */

import type { ExportDataset } from './expenseExportService';

export async function generateXlsxBlob(dataset: ExportDataset): Promise<Blob> {
  const XLSX = await import('xlsx');

  const wb = XLSX.utils.book_new();

  // ═══════════════════════════════════════════════════════
  // Sheet 1 — Summary
  // ═══════════════════════════════════════════════════════
  const summaryData = [
    ['RoomMate — Personal Expense Report'],
    [''],
    ['Month', dataset.monthLabel],
    ['Generated By', dataset.userName],
    ['Generated On', new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })],
    [''],
    ['── Financial Summary ──'],
    ['Personal Spending', dataset.totalPersonalSpending],
    ['Shared Expenses', dataset.totalSharedContribution],
    ['Total Spending', dataset.totalOverallSpending],
    [''],
    ['Monthly Budget', dataset.monthlyBudget],
    ['Budget Used', `${dataset.budgetUsedPercent}%`],
    ['Remaining Budget', dataset.remainingBudget],
    [''],
    ['Average Daily Spend', dataset.avgDailySpending],
    ...(dataset.safeDailyLimit > 0 ? [['Safe Daily Limit', dataset.safeDailyLimit]] : []),
    ['Total Transactions', dataset.transactionCount],
    [''],
    ['── Settlement Summary ──'],
    ['Amount I Need To Pay', dataset.settlementSummary.totalIOwe],
    ['Amount Others Owe Me', dataset.settlementSummary.totalOwedToMe],
    ['Settled', dataset.settlementSummary.totalSettled],
    ['Outstanding', dataset.settlementSummary.totalOutstanding],
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  wsSummary['!cols'] = [{ wch: 25 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // ═══════════════════════════════════════════════════════
  // Sheet 2 — Transactions
  // ═══════════════════════════════════════════════════════
  const txnHeader = ['Date', 'Time', 'Description', 'Category', 'Type', 'Amount', 'Shared Total', 'My Share', 'Paid By', 'Status'];
  const txnRows = dataset.transactions.map((t) => [
    t.date,
    t.time,
    t.description,
    t.category,
    t.expenseType,
    t.amount,
    t.sharedTotal ?? '',
    t.myShare ?? '',
    t.paidBy || '',
    t.paymentStatus || '',
  ]);

  const wsTransactions = XLSX.utils.aoa_to_sheet([txnHeader, ...txnRows]);
  wsTransactions['!cols'] = [
    { wch: 14 }, // Date
    { wch: 10 }, // Time
    { wch: 30 }, // Description
    { wch: 16 }, // Category
    { wch: 10 }, // Type
    { wch: 12 }, // Amount
    { wch: 14 }, // Shared Total
    { wch: 12 }, // My Share
    { wch: 16 }, // Paid By
    { wch: 14 }, // Status
  ];
  XLSX.utils.book_append_sheet(wb, wsTransactions, 'Transactions');

  // ═══════════════════════════════════════════════════════
  // Sheet 3 — Categories
  // ═══════════════════════════════════════════════════════
  const catHeader = ['Category', 'Spent', 'Target', '% Used', 'Status'];
  const catRows = dataset.categoryBreakdown
    .filter((c) => c.spent > 0 || c.cap > 0)
    .map((c) => [
      c.name,
      c.spent,
      c.cap > 0 ? c.cap : '—',
      c.cap > 0 ? `${c.percentUsed}%` : '—',
      c.status,
    ]);

  const wsCategories = XLSX.utils.aoa_to_sheet([catHeader, ...catRows]);
  wsCategories['!cols'] = [
    { wch: 18 },
    { wch: 12 },
    { wch: 12 },
    { wch: 10 },
    { wch: 16 },
  ];
  XLSX.utils.book_append_sheet(wb, wsCategories, 'Categories');

  // ═══════════════════════════════════════════════════════
  // Sheet 4 — Shared Expenses (only if present)
  // ═══════════════════════════════════════════════════════
  if (dataset.sharedContributions.length > 0) {
    const sharedHeader = ['Title', 'Category', 'Date', 'Total Amount', 'My Share', 'Paid By', 'Status'];
    const sharedRows = dataset.sharedContributions.map((sc) => {
      const d = new Date(sc.expenseDate);
      const dateStr = d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
      return [
        sc.title,
        sc.category,
        dateStr,
        sc.totalAmount,
        sc.myShare,
        sc.paidByName,
        sc.paidByMe ? 'I Paid' : 'Owed',
      ];
    });

    const wsShared = XLSX.utils.aoa_to_sheet([sharedHeader, ...sharedRows]);
    wsShared['!cols'] = [
      { wch: 25 },
      { wch: 14 },
      { wch: 14 },
      { wch: 14 },
      { wch: 12 },
      { wch: 16 },
      { wch: 12 },
    ];
    XLSX.utils.book_append_sheet(wb, wsShared, 'Shared Expenses');
  }

  // ── Generate binary ──
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([wbout], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}
